In [1]:
import pandas as pd

In [3]:
df=pd.read_csv("Titanic-Dataset.csv")

In [4]:
print(df)

     PassengerId  Survived  Pclass  \
0              1         0       3
1              2         1       1
2              3         1       3
3              4         1       1
4              5         0       3
..           ...       ...     ...
886          887         0       2
887          888         1       1
888          889         0       3
889          890         1       1
890          891         0       3

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1
2                               Heikkinen, Miss. Laina  female  26.0      0
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1
4                             Allen, Mr. William Henry    male  35.0      0
..                                                 ...     ...   ...    ...
886                              Montvila, Rev. Juozas    male  27.0      0
887                       Graham, Miss. Margaret Edith  female  19.0      0
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1
889                              Behr, Mr. Karl Howell    male  26.0      0
890                                Dooley, Mr. Patrick    male  32.0      0

     Parch            Ticket     Fare Cabin Embarked
0        0         A/5 21171   7.2500   NaN        S
1        0          PC 17599  71.2833   C85        C
2        0  STON/O2. 3101282   7.9250   NaN        S
3        0            113803  53.1000  C123        S
4        0            373450   8.0500   NaN        S
..     ...               ...      ...   ...      ...
886      0            211536  13.0000   NaN        S
887      0            112053  30.0000   B42        S
888      2        W./C. 6607  23.4500   NaN        S
889      0            111369  30.0000  C148        C
890      0            370376   7.7500   NaN        Q

[891 rows x 12 columns]

In [5]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [10]:
df=df[['Name','Sex', 'Age','Fare','Survived']]

In [11]:
df.head()

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,1
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,1
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,1
4,"Allen, Mr. William Henry",male,35.0,8.0500,0

In [14]:
df[(df['Sex']=='male') & (df['Age']>30) & (df['Survived']==1)]

,Name,Sex,Age,Fare,Survived
21,"Beesley, Mr. Lawrence",male,34.0,13.0000,1
74,"Bing, Mr. Lee",male,32.0,56.4958,1
187,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,26.5500,1
209,"Blank, Mr. Henry",male,40.0,31.0000,1
224,"Hoyt, Mr. Frederick Maxfield",male,38.0,90.0000,1
248,"Beckwith, Mr. Richard Leonard",male,37.0,52.5542,1
288,"Hosono, Mr. Masabumi",male,42.0,13.0000,1
338,"Dahl, Mr. Karl Edwart",male,45.0,8.0500,1
390,"Carter, Mr. William Ernest",male,36.0,120.0000,1
400,"Niskanen, Mr. Juha",male,39.0,7.9250,1
414,"Sundman, Mr. Johan Julian",male,44.0,7.9250,1
429,"Pickard, Mr. Berk (Berk Trembisky)",male,32.0,8.0500,1
447,"Seward, Mr. Frederic Kimber",male,34.0,26.5500,1
449,"Peuchen, Major. Arthur Godfrey",male,52.0,30.5000,1
453,"Goldenberg, Mr. Samuel L",male,49.0,89.1042,1
460,"Anderson, Mr. Harry",male,48.0,26.5500,1
512,"McGough, Mr. James Robert",male,36.0,26.2875,1
543,"Beane, Mr. Edward",male,32.0,26.0000,1
569,"Jonsson, Mr. Carl",male,32.0,7.8542,1
570,"Harris, Mr. George",male,62.0,10.5000,1
572,"Flynn, Mr. John Irwin (""Irving"")",male,36.0,26.3875,1
579,"Jussila, Mr. Eiriik",male,32.0,7.9250,1
587,"Frolicher-Stehli, Mr. Maxmillian",male,60.0,79.2000,1
599,"Duff Gordon, Sir. Cosmo Edmund (""Mr Morgan"")",male,49.0,56.9292,1
604,"Homer, Mr. Harry (""Mr E Haven"")",male,35.0,26.5500,1
621,"Kimball, Mr. Edwin Nelson Jr",male,42.0,52.5542,1
630,"Barkworth, Mr. Algernon Henry Wilson",male,80.0,30.0000,1
632,"Stahelin-Maeglin, Dr. Max",male,32.0,30.5000,1
645,"Harper, Mr. Henry Sleeper",male,48.0,76.7292,1
647,"Simonius-Blumer, Col. Oberst Alfons",male,56.0,35.5000,1
660,"Frauenthal, Dr. Henry William",male,50.0,133.6500,1
673,"Wilhelms, Mr. Charles",male,31.0,13.0000,1
679,"Cardeza, Mr. Thomas Drake Martinez",male,36.0,512.3292,1
690,"Dick, Mr. Albert Adrian",male,31.0,57.0000,1
701,"Silverthorne, Mr. Spencer Victor",male,35.0,26.2875,1
707,"Calderhead, Mr. Edward Pennington",male,42.0,26.2875,1
712,"Taylor, Mr. Elmer Zebley",male,48.0,52.0000,1
737,"Lesurer, Mr. Gustave J",male,35.0,512.3292,1
744,"Stranden, Mr. Juho",male,31.0,7.9250,1
838,"Chip, Mr. Chang",male,32.0,56.4958,1
857,"Daly, Mr. Peter Denis",male,51.0,26.5500,1

In [15]:
df['Survived']=df['Survived'].astype(bool)

In [16]:
df.head()

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,True
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,True
4,"Allen, Mr. William Henry",male,35.0,8.0500,False

In [17]:
new_df=df[(df['Sex']=='male') & (df['Age']>30) & (df['Survived']==1)]

In [18]:
print(new_df)

                                              Name   Sex   Age      Fare  \
21                           Beesley, Mr. Lawrence  male  34.0   13.0000
74                                   Bing, Mr. Lee  male  32.0   56.4958
187  Romaine, Mr. Charles Hallace ("Mr C Rolmane")  male  45.0   26.5500
209                               Blank, Mr. Henry  male  40.0   31.0000
224                   Hoyt, Mr. Frederick Maxfield  male  38.0   90.0000
248                  Beckwith, Mr. Richard Leonard  male  37.0   52.5542
288                           Hosono, Mr. Masabumi  male  42.0   13.0000
338                          Dahl, Mr. Karl Edwart  male  45.0    8.0500
390                     Carter, Mr. William Ernest  male  36.0  120.0000
400                             Niskanen, Mr. Juha  male  39.0    7.9250
414                      Sundman, Mr. Johan Julian  male  44.0    7.9250
429             Pickard, Mr. Berk (Berk Trembisky)  male  32.0    8.0500
447                    Seward, Mr. Frederic Kimber  male  34.0   26.5500
449                 Peuchen, Major. Arthur Godfrey  male  52.0   30.5000
453                       Goldenberg, Mr. Samuel L  male  49.0   89.1042
460                            Anderson, Mr. Harry  male  48.0   26.5500
512                      McGough, Mr. James Robert  male  36.0   26.2875
543                              Beane, Mr. Edward  male  32.0   26.0000
569                              Jonsson, Mr. Carl  male  32.0    7.8542
570                             Harris, Mr. George  male  62.0   10.5000
572               Flynn, Mr. John Irwin ("Irving")  male  36.0   26.3875
579                            Jussila, Mr. Eiriik  male  32.0    7.9250
587               Frolicher-Stehli, Mr. Maxmillian  male  60.0   79.2000
599   Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")  male  49.0   56.9292
604                Homer, Mr. Harry ("Mr E Haven")  male  35.0   26.5500
621                   Kimball, Mr. Edwin Nelson Jr  male  42.0   52.5542
630           Barkworth, Mr. Algernon Henry Wilson  male  80.0   30.0000
632                      Stahelin-Maeglin, Dr. Max  male  32.0   30.5000
645                      Harper, Mr. Henry Sleeper  male  48.0   76.7292
647            Simonius-Blumer, Col. Oberst Alfons  male  56.0   35.5000
660                  Frauenthal, Dr. Henry William  male  50.0  133.6500
673                          Wilhelms, Mr. Charles  male  31.0   13.0000
679             Cardeza, Mr. Thomas Drake Martinez  male  36.0  512.3292
690                        Dick, Mr. Albert Adrian  male  31.0   57.0000
701               Silverthorne, Mr. Spencer Victor  male  35.0   26.2875
707              Calderhead, Mr. Edward Pennington  male  42.0   26.2875
712                       Taylor, Mr. Elmer Zebley  male  48.0   52.0000
737                         Lesurer, Mr. Gustave J  male  35.0  512.3292
744                             Stranden, Mr. Juho  male  31.0    7.9250
838                                Chip, Mr. Chang  male  32.0   56.4958
857                         Daly, Mr. Peter Denis   male  51.0   26.5500

     Survived
21       True
74       True
187      True
209      True
224      True
248      True
288      True
338      True
390      True
400      True
414      True
429      True
447      True
449      True
453      True
460      True
512      True
543      True
569      True
570      True
572      True
579      True
587      True
599      True
604      True
621      True
630      True
632      True
645      True
647      True
660      True
673      True
679      True
690      True
701      True
707      True
712      True
737      True
744      True
838      True
857      True

In [19]:
new_df.head()

,Name,Sex,Age,Fare,Survived
21,"Beesley, Mr. Lawrence",male,34.0,13.0000,True
74,"Bing, Mr. Lee",male,32.0,56.4958,True
187,"Romaine, Mr. Charles Hallace (""Mr C Rolmane"")",male,45.0,26.5500,True
209,"Blank, Mr. Henry",male,40.0,31.0000,True
224,"Hoyt, Mr. Frederick Maxfield",male,38.0,90.0000,True

In [23]:
print(df.columns)

Index(['Name', 'Sex', 'Age', 'Fare', 'Survived'], dtype='object')

In [25]:
df.head()

,Name,Sex,Age,Fare,Survived
0,"Braund, Mr. Owen Harris",male,22.0,7.2500,False
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,71.2833,True
2,"Heikkinen, Miss. Laina",female,26.0,7.9250,True
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,53.1000,True
4,"Allen, Mr. William Henry",male,35.0,8.0500,False

In [26]:
df=pd.read_csv("Titanic-Dataset.csv")

In [28]:
df=df[['Pclass', 'Sex', 'Age', 'Fare', 'Survived']]

In [29]:
df.groupby('Pclass').agg(
    survival_rate=('Survived', 'mean'),
    avg_fare=('Fare', 'mean'),
    avg_age=('Age', 'mean')
).round(2)

        survival_rate  avg_fare  avg_age
Pclass
1                0.63     84.15    38.23
2                0.47     20.66    29.88
3                0.24     13.68    25.14